code --install-extension aaron-bond.better-comments
code --install-extension GitHub.vscode-github-actions
code --install-extension alexowl.transparent-color-theme
code --install-extension ms-python.vscode-pylance
code --install-extension dzhavat.bracket-pair-toggler
code --install-extension donjayamanne.python-extension-pack
code --install-extension vscode-icons-team.vscode-icons
code --install-extension esbenp.prettier-vscode
code --install-extension yzhang.markdown-all-in-one
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension bierner.markdown-preview-github-styles
code --install-extension hediet.vscode-drawio
code --install-extension ms-azuretools.vscode-docker
code --install-extension foxundermoon.shell-format
code --install-extension eamodio.gitlens
code --install-extension wesbos.theme-cobalt2
code --install-extension johnpapa.vscode-peacock
code --install-extension Gruntfuggly.todo-tree
code --install-extension dotenv.dotenv-vscode
code --install-extension owenfarrell.vscode-vault
code --install-extension redhat.vscode-yaml
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-toolsai.jupyter
code --install-extension ionutvmi.reg